### ISSUE TITLE
The DTLS handshake timed out at Socket.expectHandshake

### ISSUE THREAD

**Issue by mandray** [AlCalzone/node-dtls-client#315]
I'm trying to use this with Hue entertainment and when trying to close the socket and open it back up. I always run into this without fail. Not sure if there's something wrong with the closing or what

**Comment by AlCalzone** [comment]
I'm a bit rusty on the details, but I think that is because the other party failed to respond to a handshake request in time. You'll probably have to capture the raw traffic with Wireshark to figure out what's happening differently on the subsequent connection.

Does the same happen if you instead create a new socket?

**Comment by cipher2k** [comment]
I have the same issue since yesterday. It suddenly stopped working for me with the same error.

It may have something to do with the latest tradfri Gateway update, but I can not verify if this was the exact moment when it stopped working.

Is there anything I can do to look further into it?

**Comment by AlCalzone** [comment]
If you're talking to a tradfri gateway, you should use `node-tradfri-client` instead. That has a bug in its newest DTLS implementation that reuses the sequence number once during the handshake. 

If you absolutely need to stay on this library, I've added a workaround in versions 1.0.1 / 0.7.1 - search for `resetAntiReplayWindowBeforeServerHello` in the README.

**Comment by cipher2k** [comment]
I am using [https://github.com/hemtjanst/tradfri-mqtt](url) and this seems to rely on your DTLS implementation. Do I need to change anything in the code in order use the workaround or is it applied automatically after an update to 1.0.1 / 0.7.1 ? Because, I have updated the module, but tradfri-mqtt still fails with the same exception in node-dtls-client .

**Comment by AlCalzone** [comment]
Ok that indirectly depends on this library. Essentially that project needs to update `node-coap-client` to `1.0.9` or `2.0.1` and do this:
https://github.com/AlCalzone/node-tradfri-client/commit/dd077ff949fd1cd356a4528aa32f9d2bac8fa6f2#diff-c8241e4ec64dc787f3bedf021daf546c837ab68577fa74d2374a22c0ecb4e1d8

**Comment by cipher2k** [comment]
Thanks for the quick reply. I already forked that project and updated it to use your workaround. It works now.
